[package]
name = "test-component"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.6.0" }

[lib]
path = "src/lib.rs"
name = "lib"
crate-type = ["cdylib"]

